# Generated by Django 4.0.1 on 2022-01-24 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoproduct',
            name='os_platform',
            field=models.CharField(choices=[('Window', 'Window'), ('Linux', 'Linux'), ('MacOS', 'MacOS')], max_length=255),
        ),
    ]
