# Generated by Django 4.0.1 on 2022-01-25 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo_customer_action', '0002_remove_objectinfo_model_action_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='path',
        ),
        migrations.CreateModel(
            name='ActionPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('action_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='geo_customer_action.action')),
            ],
        ),
    ]
