# Generated by Django 4.0.1 on 2022-01-25 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('geo_customer_action', '0006_action_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='model',
        ),
        migrations.RemoveField(
            model_name='objectinfo',
            name='action_id',
        ),
        migrations.AddField(
            model_name='action',
            name='object_info',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='geo_customer_action.objectinfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='objectinfo',
            name='model',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='actionpath',
            name='path',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='objectinfo',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
