# Generated by Django 4.0.1 on 2022-01-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_customer_action', '0007_remove_action_model_remove_objectinfo_action_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='actiondatavalue',
            name='key_id',
        ),
        migrations.DeleteModel(
            name='ActionDataKey',
        ),
        migrations.DeleteModel(
            name='ActionDataValue',
        ),
        migrations.AddField(
            model_name='action',
            name='data',
            field=models.ManyToManyField(blank=True, to='geo_customer_action.ActionData'),
        ),
    ]
